### ISSUE TITLE
upload template file button would give no response if previous upload failed.

### ISSUE THREAD

**Issue by zsynacl** [kaiyuanshe/open-hackathon#654]
When I uploaded a template which was  downloaded from [templates list](http://hacking.kaiyuanshe.cn/template) and got an error response , the next upload attempt would do nothing(client and server got no request).

I first downloaded the `opentech-ubuntu-sshd.js` and changed the `provider` to custom type and uploaded as a template when creating an environment template, then I got an error in server and a tip in web page. And then I pressed upload button again but nothing happend except the browser let me chose a file.

**Comment by juniwang** [comment]
Were you testing on your local or some other environment? Is there any log/console output?

**Comment by zsynacl** [comment]
no. I didn't get any thing on my server or client output. I guess maybe something wrong with javascript. I didn't test whether it would happen if I uploaded the first template successfully.

the first attempt goes here(I modified the provider to 10 which was not supported):
```
2016-08-18 11:50:54,320 - INFO(Thread-156) - 192.168.3.13 - - [18/Aug/2016 11:50:54] "OPTIONS /api/template/file HTTP/1.1" 200 -
2016-08-18 11:50:54,365 - DEBUG(Thread-157) - create template from file: {u'virtual_environments': [{u'Hostname': u'', u'SecurityOpts': [u''], u'Entrypoint': u'', u'Env': [], u'NetworkDisabled': False, u'MacAddress': u'', u'User': u'', u'provider': u'10', u'OpenStdin': True, u'AttachStderr': True, u'type': u'ubuntu terminal', u'AttachStdout': True, u'description': u'ubuntu', u'WorkingDir': u'', u'Cmd': [], u'StdinOnce': True, u'AttachStdin': False, u'Volumes': {}, u'Tty': True, u'remote': {u'username': u'root', u'password': u'root', u'protocol': u'ssh', u'port': 22, u'provider': u'guacamole'}, u'name': u'ubuntu', u'Domainname': u'', u'Image': u'junbowang/ubuntu-sshd', u'Labels': {}, u'HostConfig': {u'Dns': [], u'Memory': 0, u'DnsSearch': [], u'Privileged': False, u'CpusetCpus': u'', u'CgroupParent': u'', u'RestartPolicy': {u'MaximumRetryCount': 0, u'Name': u''}, u'PublishAllPorts': False, u'ReadonlyRootfs': False, u'CpuShares': 0, u'NetworkMode': u'', u'LxcConf': {}, u'Devices': [], u'VolumesFrom': [], u'Binds': [], u'MemorySwap': 0, u'ExtraHosts': [], u'Ulimits': [], u'CapDrop': [], u'Links': [], u'PortBindings': {}, u'CapAdd': [], u'LogConfig': {u'Config': {}, u'Type': u'json-file'}}, u'ExposedPorts': {}, u'ports': [{u'protocol': u'tcp', u'port': 22, u'name': u'sshd', u'public': True}]}], u'name': u'opentech-ubuntu-sshd', u'description': u'basic ubuntu image with keep-alive sshd'}
2016-08-18 11:50:54,366 - ERROR(Thread-157) - unsupported virtual environment provider
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 397, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 487, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/zsy/hackathon/open-hackathon/open-hackathon-server/src/hackathon/views/hackathon_resource.py", line 102, in wrapper
    output_data = func(*args, **kwargs)
  File "/home/zsy/hackathon/open-hackathon/open-hackathon-server/src/hackathon/decorators.py", line 47, in authenticate_and_call
    return func(*args, **kwargs)
  File "/home/zsy/hackathon/open-hackathon/open-hackathon-server/src/hackathon/views/resources.py", line 106, in post
    return template_library.create_template_by_file()
  File "/home/zsy/hackathon/open-hackathon/open-hackathon-server/src/hackathon/template/template_library.py", line 116, in create_template_by_file
    template_content = self.__load_template_content(template_dic)
  File "/home/zsy/hackathon/open-hackathon/open-hackathon-server/src/hackathon/template/template_library.py", line 291, in __load_template_content
    return TemplateContent.from_dict(args)
  File "/home/zsy/hackathon/open-hackathon/open-hackathon-server/src/hackathon/template/template_content.py", line 66, in from_dict
    units = map(convert_to_unit, args[TEMPLATE.VIRTUAL_ENVIRONMENTS])
  File "/home/zsy/hackathon/open-hackathon/open-hackathon-server/src/hackathon/template/template_content.py", line 64, in convert_to_unit
    raise Exception("unsupported virtual environment provider")
Exception: unsupported virtual environment provider
2016-08-18 11:50:54,491 - DEBUG(Thread-157) - response with code: 500 and message: unsupported virtual environment provider
2016-08-18 11:50:54,493 - INFO(Thread-157) - 192.168.3.13 - - [18/Aug/2016 11:50:54] "POST /api/template/file HTTP/1.1" 200 -
```

then I tried to upload again, but nothing happend on client or server console.

**Comment by zsynacl** [comment]
I deployed client and server on a virtual machine which was bridged into the same network. And the config.py was changed accordingly.

**Comment by juniwang** [comment]
the message is quite clear: `Exception: unsupported virtual environment provider`. So a new provider must be implemented before using
