### ISSUE TITLE
setup_db.py failed

### ISSUE THREAD

**Issue by chensong2000** [kaiyuanshe/open-hackathon#660]
I tried to run the project following the developer guide, but got blocked when running setup_db.py,here is the error info:
Traceback (most recent call last):
  File "open-hackathon-server/src/setup_db.py", line 55, in <module>
    setup_db()
  File "open-hackathon-server/src/setup_db.py", line 52, in setup_db
    User.objects(name="admin").update_one(__raw__={"$set": admin.to_mongo().to_dict()}, upsert=True)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 210, in _get_collection
    cls.ensure_indexes()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 766, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1380, in create_index
    self.__create_index(keys, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1290, in __create_index
    sock_info, cmd, read_preference=ReadPreference.PRIMARY)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 205, in _command
    read_concern=read_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 213, in command
    read_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 101, in command
    helpers._check_command_response(response_doc, msg, allowable_errors)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 196, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('createIndexes', u'user'), ('indexes', [{'unqiue': True, 'background': False, 'sparse': True, 'key': SON([('provider', 1), ('openid', 1)]), 'name': u'provider_1_openid_1'}])]) on namespace hackathon.$cmd failed: The field 'unqiue' is not valid for an index specification. Specification: { unqiue: true, background: false, sparse: true, key: { provider: 1, openid: 1 }, name: "provider_1_openid_1" }

Environment:
ubuntu 16.04
mongodb v4.0.4

**Comment by juniwang** [comment]
Is this still a problem?  Would you plz try it on the mongo CLI?

**Comment by chensong2000** [comment]
Finally i found the problem.In models.py, "unique" is misspelled as "unqiue". 
Hackathon is working fine in my laptop after it's fixed.
I will upload a new patch soon.
